version: '3.8'

services:
  backend:
    image: laiba777/sabza-backend:v2
    container_name: sabza-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: always

  frontend:
    image: laiba777/sabza-frontend:v2
    container_name: sabza-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=/api
    depends_on:
      - backend
    restart: always
