apiVersion: v1
kind: Service
metadata:
  name: sabza-frontend-service
  namespace: sabza-landingpage-2
  labels:
    app: sabza-frontend
spec:
  type: ClusterIP
  selector:
    app: sabza-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
